# Generated by Django 2.1.8 on 2019-07-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='project',
            new_name='module',
        ),
    ]
