# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190502_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='describe',
            field=models.TextField(max_length=50, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=1, verbose_name='状态'),
        ),
    ]
